[libraries]
bson = { module = "org.mongodb:bson", version = "5.6.3" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version = "1.0.0" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version = "1.1.1" }
